### ISSUE TITLE
exampleJava uses version 3.1.0 of pvDataJava and pvAccessJava

### ISSUE THREAD

**Issue by ralphlange** [epics-base/exampleJava#1]
The Java example still uses the 3.x series of pvData/pvAccess. Old API and such.

**Comment by dhickin** [comment]
Which "example" -  helloWorld, rdbService or both.
Which methods are you specifically referring to? 

Note the only thing marked as deprecated in the Javadoc in pvDataJava is PvAuxInfo, although the getStringField etc. methods in PVStructure are marked //@Deprecated with a capital D outside the Javadoc. I can't find anything deprecated in pvAccessJava.

getStringField is used in exampleJava - is this what you're referring to?

**Comment by ralphlange** [comment]
I am referring to the pom:

``` xml
    <dependencies>
        ...
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>pvDataJava</artifactId>
            <version>3.1.0</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>pvAccessJava</artifactId>
            <version>3.1.0</version>
        </dependency>
    </dependencies>
```

**Comment by mrkraimer** [comment]
This is no longer true.

Many changed have been made to exampleJava since this issue was raised.
