### ISSUE TITLE
Fix redundancies in documentation

### ISSUE THREAD

**Issue by ralphlange** [epics-base/exampleJava#19]
The documentation for running the examples is partially repeated in up to three places:
- the submodule's README
- the submodule's `documentation/<module>.html`
- the parent module's `documentation/exampleJava.html`

Such redundancy is confusing, error-prone, and hard to maintain.

**Comment by ralphlange** [comment]
A user working on the examples should have _one_ manual to follow. (The current structure has 30 possible places for documentation.)

If an example application is copied out as a starting point for creating a new application (which is an intended use case as per the top level README), it should not contain boilerplate documentation that only applies to the original example.
However, the copied-out example may have a short generic README that describes building the application - that would still be valid for the new application.

Proposal:
- Top level README: describes building the whole thing (for all platforms) and points to `documentation/exampleJava.html` for the usage.
- Submodule README: generically describes building the module (for all platforms).
- Top level `documentation/exampleJava.html` is a parent document, describing the build and giving an overview, then linking to each `./<module>.html` (in the same directory!) for describing each example in detail.
- Top level `documentation/<module>.html` link back to the appropriate chapter in `exampleJava.html` for the build, then describe running the module's example in detail.
- Submodules have no `documentation` directories.

**Comment by ralphlange** [comment]
_**Note:** I put this on the agenda for the [Telecon on 23-Aug-2016](https://docs.google.com/document/d/1ds9KgnH6ROsIiUvmqrxVoU4XpjjK-ovI4GU8X-_hClw/pub) for discussion, agreement and decision._

**Comment by mrkraimer** [comment]
I welcome the discussion.
I have struggled about where to put documentation.

Note that in addition to exampleJava and exampleCPP there is also:
http://epics-pvdata.sourceforge.net/informative/developerGuide/developerGuide.html
My intention is that this is the first place users should look.

**Comment by ralphlange** [comment]
Structure has been changed according to the suggestion.
(Fixed in commit 190fc5914819233e0c068d3c3b55214bd27b4501.)
